config/routes.rb
Rails.application.routes.draw do
  root 'comics#index'
  resources :comics, only: [:show, :index], param: :url_slug, path: "comic" do
    match :search, to: 'comics#index', via: :post, on: :collection
  end

  namespace :admin do
    get '', to: 'dashboard#index', as: '/'
    resources :comics
  end

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'

  get '/signup' => 'users#new'
  post '/users' => 'users#create'

  get 'feed.rss', to: 'feeds#rss', :format => 'rss'

end

app/models/comic.rb
class Comic < ActiveRecord::Base
  before_validation :slug_url, :add_root_url, :ensure_post_date
  before_validation :slug_url, :add_root_url

  ROOT_URL = ""

  def slug_url
    unless self.url_slug
      self.url_slug = self.title.parameterize
    end
  end

  def add_root_url
    unless self.img_url =~ /^(http|https):\/\//
      self.img_url = File.join(ROOT_URL, self.img_url)
    end
  end

  def ensure_post_date
    unless self.post_date
      self.post_date = Time.now
    end
  end

  def self.first_comic
    self.where(visible: true).order(:post_date).first
  end

  def self.latest_comic
    self.where(visible: true).order(:post_date).last
  end

  def self.random_comic(current_comic)
    random_comic = Comic.where(visible: true).sample
    until random_comic != current_comic
      random_comic = Comic.random_comic(current_comic)
    end
    random_comic
  end

  def self.next_comic(current_comic)
    Comic.
      where('visible = ?', true).
      where('post_date > ?', current_comic.post_date).
      order(:post_date).
      first

  end

  def self.previous_comic(current_comic)
    Comic.
      where('visible = ?', true).
      where('post_date < ?', current_comic.post_date).
      order(:post_date).
      last
  end
  
end

app/models/user.rb
class User < ActiveRecord::Base

  has_secure_password

  def can_publish?
    role == "publisher"
  end

end

app/controllers/admin/comics_controller.rb
class Admin::ComicsController < ApplicationController
  before_filter :authorize
  before_filter :publisher

  def index
    @search = Comic.search(params[:q])
    @comic = Comic.new
    @comics = Comic.order(post_date: :desc)
  end

  def create
    @comic = Comic.new(comic_params)
    if @comic.save
      flash[:notice] = "Comic Posted Successfully"
      flash[:color] = "valid"
    else
      flash[:notice] = "Comic Unable to Save"
      flash[:color] = "valid"
    end
    @comics = Comic.order(post_date: :desc)
    redirect_to '/admin/comics'
  end

  def show

  end

  def edit
    @search = Comic.search(params[:q])
    @comic = Comic.find(params[:id])
  end

  def update
    @search = Comic.search(params[:q])
    @comic = Comic.find(params[:id])
    @comic.update_attributes(comic_params)
    flash[:success] = "Comic updated!"
    redirect_to '/admin/comics'
  end

  def destroy
    Comic.find(params[:id]).destroy
    flash[:success] = "Comic deleted!"
    redirect_to '/admin/comics'
  end

  private
  
  def comic_params
    params.require(:comic).permit(:title, :alt_text, :img_url, :visible, :post_date, :keywords)
  end

end

app/controllers/admin/dashboard_controller.rb
class Admin::DashboardController < ApplicationController
  before_filter :authorize
  before_filter :publisher

  def index
    @comic = Comic.new
    @comics = Comic.order(post_date: :desc)
    @search = Comic.search(params[:q])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user

  def authorize
    redirect_to '/login' unless current_user
  end

  def publisher
    redirect_to '/login' unless current_user.can_publish?
  end

end

app/controllers/comics_controller.rb
class ComicsController < ApplicationController

  def index
    @search = Comic.search(params[:q])
    if params[:q].nil?
      @comic = Comic.latest_comic
      @previous_comic = Comic.previous_comic(@comic)
      @random_comic = Comic.random_comic(@comic)
      @next_comic = Comic.next_comic(@comic)
      @first_comic = Comic.first_comic
      @last_comic = Comic.latest_comic
    else
      @comics = @search.result
      @searched_for = params[:q][:title_or_keywords_cont]
    end
  end

  def show
    @search = Comic.search(params[:q])
    @comics = @search.result
    @comic = Comic.find_by(url_slug: params[:url_slug])
    @previous_comic = Comic.previous_comic(@comic)
    @random_comic = Comic.random_comic(@comic)
    @next_comic = Comic.next_comic(@comic)
    @first_comic = Comic.first_comic
    @last_comic = Comic.latest_comic
  end


  def new
    @comic = Comic.new
    @comics = Comic.order(post_date: :desc)
  end

  def create
    @comic = Comic.new(comic_params)
    if @comic.save
      flash[:notice] = "Comic Posted Successfully"
      flash[:color] = "valid"
    else
      flash[:notice] = "Comic Unable to Save"
      flash[:color] = "valid"
    end
    @comics = Comic.order(post_date: :desc)
    render :action => :new
  end

  private

  def comic_params
    params.require(:comic).permit(:title, :alt_text, :img_url, :post_date)
  end
end

app/controllers/feeds_controller.rb
class FeedsController < ApplicationController
  layout false

  def rss
    @comics = Comic.where('visible = ?', true).order(:post_date).last(20)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  
  def new
    @search = Comic.search(params[:q])
  end

  def create
    user = User.find_by_email(params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to admin_comics_path
    else
      redirect_to '/login'
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to '/login'
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
  end

  def create
    user = User.new(user_params)
    if user.save
      session[:user_id] = user.id
      redirect_to '/'
    else
      redirect_to '/signup'
    end
  end

  private

  def user_params
    params.require(:user).permit(:name,:email, :password, :password_confirmation)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/comics/_admin_navigation.haml
%ul
  %li.bullet--none.padding--1left.padding--0top
    = "Welcome, #{current_user.name}"
    = link_to 'Logout', logout_path 

app/views/admin/comics/edit.haml
%h2
  Edit Comic

=form_for ([:admin,@comic]) do |f|
  =f.label :title
  =f.text_field :title
  =f.label :alt_text
  =f.text_field :alt_text
  =f.label :img_url
  =f.text_field :img_url
  =f.label :visible
  =f.check_box :visible
  =f.label :post_date
  =f.datetime_local_field :post_date
  =f.label :keywords
  =f.text_field :keywords
  =f.submit
  
=image_tag(@comic.img_url, :class => "comic-image")

app/views/admin/comics/index.haml
= render "admin/comics/admin_navigation"
%div.current-comics.padding--1bottom.width--90.margin--auto
  %h2
    New Comic
  =form_for ([:admin,@comic]) do |f|
    =f.label :title
    =f.text_field :title
    =f.label :alt_text
    =f.text_field :alt_text
    =f.label :img_url
    =f.text_field :img_url
    =f.label :visible
    =f.check_box :visible
    =f.label :post_date
    =f.datetime_local_field :post_date
    =f.label :keywords
    =f.text_field :keywords
    =f.submit

  %h2.padding--1top
    All Comics
  %table.list-all-comics
    -@comics.each do |comic|
      %tr
        %td.text--center
          =comic.id if comic.id
        %td
          =link_to comic.title, comic_path(comic.url_slug)
        %td
          =comic.post_date.strftime("%B %-d, %Y at %I:%M %P") if comic.post_date
        %td.text--center
          ="Visible" if comic.visible
        %td.text--center
          =link_to 'Edit', edit_admin_comic_path(comic.id)
        %td.text--center
          =link_to 'Delete', admin_comic_path(comic.id), method: :delete

app/views/admin/dashboard/index.haml
-#%div.admin-info
  -#Welcome home, #{@current_user.name}!
-#%ul.admin-nav
  -#%li
    -#=link_to "Manage Comics", admin_comics_path
    -#= render "admin/comics/admin_navigation"
=render :template => "admin/comics/index"

app/views/comics/_comic_navigation.haml
-if @comic
  %ul#comic-navigation
    %li#first-comic
      -if @first_comic && @first_comic != @comic
        =link_to "First Comic", { :action => :show, :url_slug => @first_comic.url_slug }
      -else
        First Comic
    %li#previous-comic
      -if @previous_comic && @first_comic != @comic
        =link_to "Previous Comic", :action => :show, :url_slug => @previous_comic.url_slug
      -else
        Previous Comic
    %li#random-comic
      =link_to "Random Comic", :action => :show, :url_slug => @random_comic.url_slug
    %li#next-comic
      -if @next_comic && @next_comic != @comic
        =link_to "Next Comic", :action => :show, :url_slug => @next_comic.url_slug
      -else
        Next Comic
    %li#last-comic
      -if @last_comic && @last_comic != @comic
        =link_to "Last Comic", :action => :show, :url_slug => @last_comic.url_slug
      -else
        Last Comic

app/views/comics/_comic_search_box.haml
=content_for :search do
  =search_form_for @search, :html => {class: 'bg--dark-gray', id: 'comic_search'}, url: search_comics_path, method: :post do |f|
    =f.text_field :title_or_keywords_cont, class: "search-field", placeholder: "Search"
    =f.submit "Search", class: "btn"

app/views/comics/_footer.haml
%div.bg--gray.text--center.padding--1bottom.padding--1top
  %h4
    Footer Information

app/views/comics/_header.haml
= render "comics/comic_search_box"
%div
  %a(href="/")
    %div.bg--gray
      %h4.padding--1bottom.padding--1top.text--center
        Logo

app/views/comics/_menu.haml
D

app/views/comics/index.haml
=render :template => "comics/show", :locals => { :comic => @comic}

app/views/comics/show.haml
%div#comic-main.padding-top-10.padding-bottom-10
  -unless @comic
    %div#search-result-form
      %h3.search-results-for
        -if @comics.any?
          ="Search Results for \"#{@searched_for}\""
          %ul#search-results
            -@comics.each do |comic|
              %li.single-result
                =link_to comic.title, comic_path(comic.url_slug), class: "orange-link"
        -else
          ="Sorry, No Comics Found For \"#{@searched_for}\""
  -else
    %div#comic-and-nav-wrapper
      %div#first-comic
        -if @first_comic && @first_comic != @comic
          %a{:href => "/comic/" + @first_comic.url_slug}
            %div#first-link
              First
        -else
          First
      %div#previous-comic
        -if @previous_comic && @first_comic != @comic
          %a{:href => "/comic/" + @previous_comic.url_slug}
            %div#previous-link
              Previous
        -else
          Previous
      %div#comic-image
        %h4.comic-title.padding-top-0.padding-bottom-0.margin-top-0.margin-bottom-0
          ="\"#{@comic.title}\""
        %h5.comic-date.padding-top-0.padding-bottom-0.margin-top-0.margin-bottom-0
          =@comic.post_date.strftime(" %B %-d, %Y")
        %h6.random-link.padding-top-0.padding-bottom-10.margin-top-0.margin-bottom-0
          =link_to "Random Comic", { :action => :show, :url_slug => @random_comic.url_slug }, id: "random-link", class: "orange-link"
        -if @next_comic && @next_comic != @comic
          =link_to(image_tag(@comic.img_url, :class => "comic-image", alt: @comic.alt_text, title: @comic.alt_text), :action => :show, :url_slug => @next_comic.url_slug)
        -else
          =image_tag @comic.img_url, :class => "comic-image", alt: @comic.alt_text, title: @comic.alt_text
      %div#next-comic
        -if @next_comic && @next_comic != @comic
          %a{:href => "/comic/" + @next_comic.url_slug}
            %div#next-link
              Next
        -else
          Next
      %div#last-comic
        -if @last_comic && @last_comic != @comic
          %a{:href => "/comic/" + @last_comic.url_slug}
            %div#last-link
              Last
        -else
          Last

app/views/layouts/_footer.html.erb
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
      (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
    m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
        })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  //replace with UA ID from Google Analytics
  //ga('create', 'UA-36790335-1', 'noncanon.com');
  ga('send', 'pageview');

</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Hastings Site</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <link rel="stylesheet" href="http://yui.yahooapis.com/pure/0.6.0/pure-min.css">
  <%= csrf_meta_tags %>
  <%= auto_discovery_link_tag(:rss, root_url + "feed.rss") %>
</head>
<body>
  <%= render "comics/header" %>
    <%= yield(:search) %>
		<%= yield %>
	</div>

  <%= render "comics/footer" %>
  <%= render "layouts/footer" %>
</body>
</html>

app/views/users/new.haml
=form_for :user, url: '/users' do |f|
  =f.label :name
  =f.text_field :name
  =f.label :email
  =f.text_field :email
  =f.label :password
  =f.text_field :password
  =f.label :password_confirmation
  =f.text_field :password_confirmation
  =f.submit